services:
  single:
    container_name: hcm-generate-labels-single-project
    image: node:lts-alpine3.20
    environment:
      - TABLE_NAME=TAPPLSCR
    volumes:
      - ./single/app.js:/home/node/app/app.js
      - ./source/single:/home/node/app/source
    user: node
    working_dir: /home/node/app
    command: ["node", "app.js"]

  statement:
    container_name: hcm-generate-labels-sql-statement
    image: node:lts-alpine3.20
    environment:
      - HOME_DIR=/home/node
    volumes:
      - ./statement/app:/home/node/app
      - ./source/statement:/home/node/source
    user: node
    working_dir: /home/node/app
    command: ["npm", "start"]
